server:
  port: 8080 

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Pumas12.
    url: jdbc:postgresql://localhost/test
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
        